tools:
  - class_name: recipe.med.vision_tool.ImageCropAndZoomInTool
    config:
      vision_service_url: http://127.0.0.1:8000/image_crop_and_zoom_in_tool
      num_workers: 120
      rate_limit: 120
      timeout: 30
      reward: 1.0
      penalty: 0
      type: native
    tool_schema:
      type: function
      function:
        name: image_crop_and_zoom_in_tool
        description: Crops and zooms into a specific region of an image based on provided relative coordinates. All coordinate values should be float numbers with the range [0,1000.0].
        parameters:
          type: object
          properties:
            bbox_2d:
              type: array
              items:
                type: number
              minItems: 4
              maxItems: 4
              description: Defines the rectangular area for cropping in the format [x1, y1, x2, y2]. (x1, y1) marks the upper-left corner, and (x2, y2) marks the lower-right corner. All coordinates must be in the range [0, 1000] with x1 < x2 and y1 < y2.
            label:
              type: string
              description: A descriptive name for the object within the cropped region.
            image_index:
              type: number
              description: The index of the image to apply the crop and zoom operation on, starting from 0.
          required:
            - bbox_2d
            - label
            - image_index
          strict: True
